language: node_js
env:
  - CI=false
cache:
  yarn: true
node_js:
  - "node"
  - "lts/*"
before_install:
  - npm install -g yarn
  - npm install -g lerna
install:
  - yarn bootstrap
script:
  - yarn build
